env:
  global:
  - REPO_DIR=.
  - TEST_DEPENDS="pytest"
  - PLAT=x86_64
  - CONFIG_PATH="ci/multibuild_config.sh"
language: python
python: 3.5
sudo: required
dist: trusty
services: docker
cache:
  directories:
  - "$HOME/.ccache"
matrix:
  exclude:
  - python: 3.5
  include:
  - os: linux
    env:
    - MB_PYTHON_VERSION=2.7
    - PLAT=i686
    - USE_CCACHE=1
    - FREETYPEPY_BUNDLE_FT=1
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6
    - USE_CCACHE=1
    - FREETYPEPY_BUNDLE_FT=1
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6
    - USE_CCACHE=1
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION=3.6
    - FREETYPEPY_BUNDLE_FT=1
before_install:
- source ci/multibuild/common_utils.sh
- source ci/multibuild/travis_steps.sh
- before_install
install:
- build_wheel $REPO_DIR $PLAT
script:
- install_run $PLAT
after_success:
- if [ -n "$TRAVIS_TAG" ]; then mkdir -p dist; cp wheelhouse/*.whl dist; fi
deploy:
  provider: pypi
  on:
    repo: rougier/freetype-py
    tags: true
    all_branches: true
  user: NicolasRougier
  password:
    secure: DcRKZzasCgo6eCZ5CN/tVngfCcQY7+S8MKpKIGOx4FgfrNd3P3WIxXWqHeIdDpJZKO8wqW9OIrbEvzozMvj6Y/ckcxUsAaPj3zBn80XB9oGjGLHlFCVp39rTQ3BJAOq+0UwaRQAasTErf/0Q1k1LSOttmIGW41u5zNDohwaGxgc=
  skip_cleanup: true
  distributions: check
